### ISSUE TITLE
6.3. Liệt kê các chân điều khiển tín hiệu Digital trên Arduino?

### ISSUE THREAD

**Issue by phmqngvu** [phmqngvu/Lop-11A09-Nhom-8#11]

**Comment by nguyenthuymytrang** [comment]
alo

**Comment by ngvietkorea** [comment]
alo

**Comment by ngvietkorea** [comment]
chân điều khiển tính hiệu digital là digital in và digital out

**Comment by ngvietkorea** [comment]
phải kh trang

**Comment by nguyenthuymytrang** [comment]
đúng rùi có analog in với analog out nữa

**Comment by ngvietkorea** [comment]
ụa cái này là digital sao có analog nữa v

**Comment by nguyenthuymytrang** [comment]
thì chân analog out với analog in có điều khiển tin hiệu digital nữa mà

**Comment by ngvietkorea** [comment]
à v à

**Comment by nguyenthuymytrang** [comment]
oke chốt đáp án là chân digital in với digital out và analog in với analog out nhe

**Comment by ngvietkorea** [comment]
uke

**Comment by phmqngvu** [comment]
mấy th này t kiu thầy trừ điểm giờ

**Comment by phmqngvu** [comment]
=)))))))))))

**Comment by nguyenthuymytrang** [comment]
sao v

**Comment by phmqngvu** [comment]
câu hỏi kiu kể tên chân nào mà

**Comment by phmqngvu** [comment]
![A3F5ADEA-9121-4B1E-A37F-A6F852F4ABB8](https://user-images.githubusercontent.com/91948093/140604928-b6d303e5-8216-4ad8-a06f-f785571acb0a.jpeg)

**Comment by phmqngvu** [comment]
xin lỗi thầy đi

**Comment by nguyenthuymytrang** [comment]
dạ xin lỗi thầy hiền đẹp trai nhiều ạ lỗi em

**Comment by ngvietkorea** [comment]
dạ em xin lỗi thầy

**Comment by nguyenthuymytrang** [comment]
ròi mng đáp án là chân từ 0 đến 13 là vừa digital in vừa digital out luôn nha ngoài ra còn dùng cho analog out nữa

**Comment by nguyenthuymytrang** [comment]
với thêm chân analog in từ A0 đến A5 nhe

**Comment by ngvietkorea** [comment]
à oke trang tui hiểu rồi
